# Generated by Django 5.1.1 on 2024-09-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='bids',
            new_name='highest_bid',
        ),
    ]
