# Generated by Django 5.1.1 on 2024-09-26 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_categories_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='highest_bid',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('bidder', models.ManyToManyField(blank=True, related_name='bidding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.ManyToManyField(blank=True, related_name='biddings', to='auctions.biddings'),
        ),
    ]
