# Generated by Django 5.1.1 on 2024-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
                ('bids', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
